### ISSUE TITLE
Getting 304 for http://127.0.0.1:3000/stream/index.m3u8

### ISSUE THREAD

**Issue by billytotochan** [Saren-Arterius/viu-proxy#2]
# EXTM3U #EXT-X-VERSION:4 #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="chi_1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="chi",URI="stream6/streamPlaylist.m3u8" #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="chi_2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="chi",URI="stream7/streamPlaylist.m3u8" #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=472178,CODECS="avc1.66.30",RESOLUTION=480x270,AUDIO="audio" stream1/streamPlaylist.m3u8 #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=186115,CODECS="avc1.66.31",RESOLUTION=420x240,AUDIO="audio" stream5/streamPlaylist.m3u8 #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=957504,CODECS="avc1.66.31",RESOLUTION=640x360,AUDIO="audio" stream2/streamPlaylist.m3u8 #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2281678,CODECS="avc1.66.31",RESOLUTION=1280x720,AUDIO="audio" stream3/streamPlaylist.m3u8 #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3021417,CODECS="avc1.66.40",RESOLUTION=1920x1080,AUDIO="audio" stream4/streamPlaylist.m3u8

**Comment by Saren-Arterius** [comment]
It's assumed index.m3u8's content wont change unless endpoint url got
changed. 304 should be normal.

billytotochan notifications@github.com 於 2016年4月11日 週一 05:11 寫道：
