### ISSUE TITLE
Video is ok but no sound.

### ISSUE THREAD

**Issue by 556556bt** [Saren-Arterius/viu-proxy#3]
Video is ok but no sound.

**Comment by hklcf** [comment]
@556556bt use https://www.hlsplayer.net/  or ffplay to play

**Comment by Saren-Arterius** [comment]
唔關個proxy事，upstream link都係要specify audio m3u8/改用特別既player先有聲

HKLCF notifications@github.com 於 2016年4月11日 週一 15:01 寫道：

**Comment by 556556bt** [comment]
除左https://www.hlsplayer.net等online player? 有咩player 可以?
potplayer 可以FHD 但無聲, VLC 好low resx 又無聲. 

HLSPLAYER 有無download 落黎放自己個server, 因為唔太想開port.

**Comment by hklcf** [comment]
mpc-hc nightly可以有聲有畫

Send from my Galaxy Note 3
2016/4/11 5:16 下午 於 "556556bt" notifications@github.com 寫道：

**Comment by Saren-Arterius** [comment]
Confirmed upstream .m3u8 problem

**Comment by 556556bt** [comment]
除了hlsplayer, 其他暫未成功
