### ISSUE TITLE
npm ERR! 

### ISSUE THREAD

**Issue by microka** [Saren-Arterius/viu-proxy#4]
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
> 1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@3.8.3
> 3 info using node@v5.10.1
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle viu-proxy@1.0.0~prestart: viu-proxy@1.0.0
> 6 silly lifecycle viu-proxy@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle viu-proxy@1.0.0~start: viu-proxy@1.0.0
> 8 verbose lifecycle viu-proxy@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle viu-proxy@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Windows\System32\viu-proxy\node_modules.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\CKLAU~1\perl5\bin;C:\Users\CK Lau\AppData\Roaming\npm
> 10 verbose lifecycle viu-proxy@1.0.0~start: CWD: C:\Windows\System32\viu-proxy
> 11 silly lifecycle viu-proxy@1.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
> 12 silly lifecycle viu-proxy@1.0.0~start: Returned: code: 1  signal: null
> 13 info lifecycle viu-proxy@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: viu-proxy@1.0.0 start: `node ./bin/www`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
> 14 verbose stack     at emitTwo (events.js:100:13)
> 14 verbose stack     at EventEmitter.emit (events.js:185:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:100:13)
> 14 verbose stack     at ChildProcess.emit (events.js:185:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:850:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> 15 verbose pkgid viu-proxy@1.0.0
> 16 verbose cwd C:\Windows\System32\viu-proxy
> 17 error Windows_NT 10.0.10586
> 18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> 19 error node v5.10.1
> 20 error npm  v3.8.3
> 21 error code ELIFECYCLE
> 22 error viu-proxy@1.0.0 start: `node ./bin/www`
> 22 error Exit status 1
> 23 error Failed at the viu-proxy@1.0.0 start script 'node ./bin/www'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the viu-proxy package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     node ./bin/www
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs viu-proxy
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls viu-proxy
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

請問這是什麼原因？

**Comment by Saren-Arterius** [comment]
打左npm install未？

microka notifications@github.com 於 2016年4月13日 週三 22:51 寫道：

**Comment by microka** [comment]
@Saren-Arterius 打咗，但依然error

> C:\Users\XXX\viu-proxy>npm install
> 
> C:\Users\XXX\viu-proxy>npm start
> 
> > viu-proxy@1.0.0 start C:\Users\XXX\viu-proxy
> > node ./bin/www
> 
> C:\Users\XXX\viu-proxy\commons.js:32
>       _indexUrl = body.asset.hls.adaptive[0];
>                             ^
> 
> TypeError: Cannot read property 'hls' of undefined
>     at Request._callback (C:\Users\XXX\viu-proxy\commons.js:32:29)
>     at Request.self.callback (C:\Users\XXX\viu-proxy\node_modules\request\request.js:200:22)
>     at emitTwo (events.js:100:13)
>     at Request.emit (events.js:185:7)
>     at Request.<anonymous> (C:\Users\XXX\viu-proxy\node_modules\request\request.js:1046:10)
>     at emitOne (events.js:95:20)
>     at Request.emit (events.js:182:7)
>     at IncomingMessage.<anonymous> (C:\Users\XXX\viu-proxy\node_modules\request\request.js:973:12)
>     at emitNone (events.js:85:20)
>     at IncomingMessage.emit (events.js:179:7)
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3
> npm ERR! code ELIFECYCLE
> npm ERR! viu-proxy@1.0.0 start: `node ./bin/www`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the viu-proxy@1.0.0 start script 'node ./bin/www'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the viu-proxy package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs viu-proxy
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls viu-proxy
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\XXX\viu-proxy\npm-debug.log

**Comment by Saren-Arterius** [comment]
睇黎viutv又改左api.....

**Comment by Saren-Arterius** [comment]
等陣，你住邊到？

**Comment by microka** [comment]
@Saren-Arterius 廣州

**Comment by Saren-Arterius** [comment]
唔洗諗啦...一定要香港IP先用得
去hostus租部vps試下
