### ISSUE TITLE
can support CORS by default? 

### ISSUE THREAD

**Issue by 556556bt** [Saren-Arterius/viu-proxy#5]
many online player cannot eat the feed due to the cros limitation

**Comment by Saren-Arterius** [comment]
你係咪指CORS？

**Comment by 556556bt** [comment]
yes yes .. 打錯... 哈哈

**Comment by Saren-Arterius** [comment]
得閒搞

**Comment by lifehome** [comment]
PR: #6

**Comment by 556556bt** [comment]
點用法?

**Comment by lifehome** [comment]
唔識用你又問？😠 自己搵HLS compatible player去播啦

**Comment by 556556bt** [comment]
I'm using it already and no good HLS Player fully compitbale to viu stream
except hlsplayer.net, the online one

My question is asking how to use the CORS function. You said it's added but
no mention if it is enabled by default or need to config or not.

**Comment by lifehome** [comment]
It's "always on" mode for CORS feature, as considering online players might be located on different domain, this feature allows the resources being accessed anywhere.

**Comment by lifehome** [comment]
Issue closed as feature accepted and implemented.
